language: java
jdk:
- oraclejdk8
before_install:
openssl aes-256-cbc -K $encrypted_7f551249d712_key -iv $encrypted_7f551249d712_iv -in team/src/main/resources/application.properties.enc -out team/src/main/resources/application.properties -d
