language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_6904a6c5d2af_key -iv $encrypted_6904a6c5d2af_iv
  -in team/src/main/resources/application.properties.enc -out team/src/main/resources/application.properties
  -d
