language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_2ddd3f68f7d9_key -iv $encrypted_2ddd3f68f7d9_iv
  -in UrlShortener/team/src/main/resources/application.properties.enc -out UrlShortener/team/src/main/resources/application.properties -d
